# This is a basic workflow to help you get started with Actions

name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-proto:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build the proto files
        run: bazel build //:connection_proto
        
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: Build files
          path: /home/runner/.cache/bazel/_bazel_runner/24242c90df7e7a084474967e4042c730/execroot/__main__/bazel-out

  # This workflow contains a single job called "build"
  build-cc:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build the C++ proto files
        run: bazel build //:connection_cc_proto
        
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: Build files
          path: /home/runner/.cache/bazel/_bazel_runner/24242c90df7e7a084474967e4042c730/execroot/__main__/bazel-out

  # This workflow contains a single job called "build"
  build-java:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build the Java proto file
        run: bazel build //:connection_java_proto
        
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: Build files
          path: /home/runner/.cache/bazel/_bazel_runner/24242c90df7e7a084474967e4042c730/execroot/__main__/bazel-out
